# Language used
language: python

# Python version used
python:
  - "3.6"

# Command to start postgresql
services:
  - postgresql

addons:
  postgresql: "9.6"

# Packages to be installed
install:
  - psql -c "CREATE DATABASE ah_code_titans;" -U postgres
  - pip install -r requirements.txt
  - pip install coveralls

#Make some migrations
before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script:
  #Command to run tests
  - coverage run --source=. manage.py test
  - coverage report
after_success:
   #send coverage to coveralls
   coveralls

# slack notifications configuration
notifications:
    slack: andela:LTXqtmTsixouhMtsFDOPnaY5
